version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ecommerce-postgres
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sa123456
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ecom-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: peterphan123/ecomapp
    container_name: ecommerce-app
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/ecommerce
      DB_USERNAME: postgres
      DB_PASSWORD: sa123456
      JWT_SECRET: mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
      JWT_EXPIRATION: 300000000
      JWT_COOKIE_NAME: springBootEcom
      FRONTEND_URL: http://localhost:5173
      IMAGE_BASE_URL: http://localhost:8080/images
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ecom-network

volumes:
  postgres-data:

networks:
  ecom-network:
    driver: bridge
